sudo: false
language: r
cache: packages

r:
  - oldrel
  - release
  - devel
  - 3.4.0
  - 3.3.3
  - 3.3.2
  - 3.3.1
  - 3.3.0
  - 3.2.5
  - 3.2.4
  - 3.2.3

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
