sudo: false
language: r
cache: packages

r:
  - oldrel
  - release
  - devel
  - 3.5.1
  - 3.5.0
  - 3.4.4
  - 3.4.3
  - 3.4.2
  - 3.4.1
  - 3.4.0

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
